# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e488c0c20d2c53424b8f05a4a4718b9398b63393e5c50d0a4262c37d776dc7007e2efeb0c9fd008b375e5f0de5dae2062b3306fd4f39275b249ad2b9303f75

test:
  secret_key_base: 1296d7b1a5815d55238d163281a40c3d6a0c050c3f7cce70db42ee23c35a00283fb66bb65a873ff20f6eace8cbd80c2ed5a88702f2d39bf7c9386a8ea00a0431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
